### ISSUE TITLE
Highchart disappears in landscape mode

### ISSUE THREAD

**Issue by Niravpatel129** [highcharts/highcharts-react-native#73] opened 2020-05-04 20:14 UTC
My highchart which is contained by a `View` disappears when the iPhone is moved into landscape mode, any way to suppress this behaviour?

Code for highchart:
```
  return (
    <View style={{ flex: 1 }}>
      <HighchartsReactNative
        useCDN={true}
        useSSL={true}
        styles={styles.container}
        options={chartOptions}
        modules={modules}
      />
    </View>
  );
```

**Comment by sebastianbochan** [comment] 2020-05-12 09:36
Hi @Niravpatel129,
Thank you for reporting, I will test it.

**Comment by DirkGitS** [comment] 2020-07-07 21:42
I have the same problem. Everything seems to work fine before the change to Landscape mode. The chart never shows up again, even not when the phone rotates back to portrait mode.

**Comment by sebastianbochan** [comment] 2020-07-15 07:32
We are debugging the problem, will let you know when find a reason.

**Comment by sebastianbochan** [comment] 2020-07-23 14:08
The problem was caused by declaration param: `orientation` in the `App.js`. Please remove that and test once more.

**Comment by sebastianbochan** [comment] 2020-08-03 11:59
The new 3.0 version is released. 

Im closing this ticket. If you will encounter any problems, please create a new ticket. In this case we will avoid confusing and keep the newest version on track.

**Closed by sebastianbochan** 2020-08-03 11:59 UTC
