### ISSUE TITLE
Chart Not Rendering on iOS and Android

### ISSUE THREAD

**Issue by userkpkpuser** [highcharts/highcharts-react-native#4] opened 2019-05-29 06:33 UTC
Hi Team, when we tried to run the sample example provided in Readme file, but the charts are not rendering and there is no error also.

**Comment by sebastianbochan** [comment] 2019-05-29 07:54
Hi @userkpkpuser,
Please let me know if you use the newest expo / npm etc ?
Is it blank screen or its not builded at all?

**Comment by ssuchanowski** [comment] 2019-06-11 13:17
When running demo via expo it works but doesn't seem to be showing anything when run normally.

I see also a blank screen, just a white background. Tested with newest `npm`. Will investigate more.

**Comment by ssuchanowski** [comment] 2019-06-11 13:33
And for me running it on Android results in:

(this is the blank view that I see on iOS)
![Screenshot 2019-06-11 at 15 32 40](https://user-images.githubusercontent.com/1038270/59276232-35dcfb80-8c5e-11e9-9217-dc9b7c2d7498.png)

**Comment by ssuchanowski** [comment] 2019-06-11 13:57
After debugging I see that `injectedJavaScript` is
 ```
"\n            var modules = [],\n                moduleCounter = modules.length,\n                hcScript;\n\n            hcScript = document.createElement('script');\n\n            hcScript.setAttribute('src', '../highcharts-files/highcharts.js');\n            hcScript.onload = function() {\n\n                if (moduleCounter === 0) {\n                    \n                Highcharts.chart(\n                'container',\n                {\"series\":[{\"data\":[1,3,2,4]}]},\n                undefined\n           ..."
```

So I think the path to the lib might be an issue here - didn't check it though.

**Comment by masiamj** [comment] 2019-06-19 00:24
Same issue here as well. Let us know about any updates! Thanks!

**Comment by DZmaj** [comment] 2019-06-19 14:12
I think this is an issue with WebView, the HighchartsReactNative.js file imports WebView from 'react-native' instead of from 'react-native-webview'. If you change it, the index.html file will render but it's just a blank page (you can check if it's actually rendering by putting an alert in a script tag and checking if it pops up).

This is all on Android - very excited about using Highcharts with React Native!

**Comment by sebastianbochan** [comment] 2019-07-02 13:43
Hi,
Which version of xCode (os) and Android studio, do you have?

**Comment by ssuchanowski** [comment] 2019-07-02 15:22
XCode 10.1 and 11.X
Android Studio 3.4.1

**Comment by sebastianbochan** [comment] 2019-07-03 09:45
I did steps:

1. Clone repo of wrapper
2. run yarn
3. run in expo, all works properly
4. call expo eject to have correct ios and android native apps
5. run the project (ios) in xCode and then in simulator

As a result all worked properly (withtout errors which you experienced).

<img width="1045" alt="Zrzut ekranu 2019-07-1 o 17 08 41" src="https://user-images.githubusercontent.com/2115686/60581911-0e261280-9d88-11e9-94b5-422426a1462b.png">


ps. Im in the process of creating docs about your case, but was not forced to do your steps to run the right demo. Did I miss something?

**Comment by ssuchanowski** [comment] 2019-07-03 16:07
Try non expo project

**Comment by SaeedZhiany** [comment] 2019-07-23 05:54
@ssuchanowski 
I'm facing this problem too. I create a simple [Github repo ](https://github.com/SaeedZhiany/highchart-react-native-setup-issue) to reproduce the problem

**Comment by sebastianbochan** [comment] 2019-08-02 09:52
Hi @SaeedZhiany,
Thank you for demo, will test as soon as possible.

**Comment by ssuchanowski** [comment] 2019-08-16 12:18
How is this going?

**Comment by Seshpenguin** [comment] 2019-08-16 13:45
I'm having this issue also with Expo 34

**Comment by ssuchanowski** [comment] 2019-08-26 19:22
@athenawisdoms that's probably just a caching issue, google this part `does not exist in the Haste module map.` and you will find a solution quickly.

**Comment by ssuchanowski** [comment] 2019-09-06 08:24
@sebastianbochan any update here?

**Comment by sebastianbochan** [comment] 2019-09-06 08:42
Hi @ssuchanowski,
Im prepared the beta-version of wrapper on separate branch (`beta-webview`). If you will be able to test it, I would be grateful for any feedback. 

Related topic:
- https://github.com/highcharts/highcharts-react-native/issues/8

**Comment by ms042087** [comment] 2019-09-07 09:49
Mine showing a blank page. Any update on this?

**Comment by sebastianbochan** [comment] 2019-09-09 11:33
@ms042087,
Let me know which version of android you have?

**Comment by ms042087** [comment] 2019-09-10 04:30
@sebastianbochan Android 9.0, compiler compileSdkVersion = 28

Finally get it done. 

Blank page or page showing html text are basically due to wrong path or Android debug mode problem. I tried to put a website URL into source, it displayed normally. Therefore, the WebView module should work fine.

Main Problem:
I think it is not possible to put local html file into WebView source in Android debug mode.
Also, the source for WebView uses `require()` which I think it is for IOS. `uri:...` should be used for Android. Using `require()` gives blank page and using `uri:...` gives html text in Android virtual device.

My Solution:
1. Change the source to
`source = {(Platform.OS == 'ios') ? require('../highcharts-layout/index.html') : { uri: 'file:///android_asset/highcharts-layout/index.html' }}`

This changes the source path of the local files based on the platforms.
Remember to import 'Platform' from 'react native'

2. Put the files (i.e. Folder: `highcharts-layout` and `highcharts-files`) to `android/app/src/main/assets` and `/ios`

3. Use release mode instead of debug mode
i.e. run `react-native run-android --variant=release`

Hope it helps.

**Comment by sebastianbochan** [comment] 2019-09-11 12:46
Hi @userkpkpuser,
Thank you for the suggestions. When I tested the solution (point 1) I had a problem (blank page) in old Android 6.

Its strickly related with webview problems like:
- 
- 


At this moment, I think that the best solution is adding platform recognizing (like you suggested) + add an option of load files prom CDN instead of local files system.

Points 2 and 3 will be only in docs (for user adaption).

Does it make sense?

**Comment by ms042087** [comment] 2019-09-20 08:05
@sebastianbochan 
yes, it makes sense to load file from CDN instead of local files system.

I retested my solution and it works for me.
Point 1 + 2 should be done together. Have you put the files to android/app/src/main/assets?
If not works, I think that maybe my solution is not suitable for old version of Android.

**Comment by sebastianbochan** [comment] 2019-09-27 13:05
Hi @ms042087,
Thank you for really big feedback and advices. I committed your suggestions (and some for iOS) on my `beta-webview` branch.

Will be really grateful if you will be able to test it too.

ps. if all will work properly I will add CDN and modules options.

**Comment by ms042087** [comment] 2019-09-27 13:55
@sebastianbochan 
yes it works for me

**Comment by sebastianbochan** [comment] 2019-09-27 14:42
Thank you for feedback, Im starting to add CDN support and multiple modules.

**Comment by BabishanM** [comment] 2019-09-28 08:16
Hi @sebastianbochan ,

Current from branch 'beta-webview', I am getting white screen.

In order to fix this issue, Do I need to follow @ms042087 steps? 
I tried but unfortunately it is not working. I ran the code in debug mode.

Am i missing something?

**Comment by ms042087** [comment] 2019-09-28 08:21
Hi @BabishanM,
Have you put the files (i.e. Folder: highcharts-layout and highcharts-files) to android/app/src/main/assets and /ios?

**Comment by BabishanM** [comment] 2019-09-28 08:30
Hi @ms042087 ,
yes I did. I copied both the folders(i.e. Folder: highcharts-layout and highcharts-files).

//Android
![Screenshot 2019-09-28 at 1 56 44 PM](https://user-images.githubusercontent.com/33688844/65813862-2e833300-e1f8-11e9-88fe-e315ca7ab343.png)

//ios
![Screenshot 2019-09-28 at 1 56 56 PM](https://user-images.githubusercontent.com/33688844/65813863-2e833300-e1f8-11e9-883a-c2af21398e68.png)

Do i need to copy only the files present inside both the folder?

**Comment by leonascimento** [comment] 2019-09-29 17:24
@sebastianbochan after to create a simple project and to install your branch through `npm install --save highcharts/highcharts-react-native#beta-webview`.

Enviroment:

expo 33 SDK version 
node: v10.13.0
npm: 6.4.1
OS: macOS Mojave 10.14.5
Android version: 9

I tried an example from the readme and this is not working yet.
![Screenshot_20190929-140928](https://user-images.githubusercontent.com/3650251/65835999-a5393280-e2c3-11e9-8ed5-4490f4f481f5.png)

**Comment by Jessica7** [comment] 2019-09-29 17:34
I had the same problem as well :(

**Comment by sebastianbochan** [comment] 2019-09-30 10:13
@ms042087,
Are you able to reproduce the problem?

**Comment by leonascimento** [comment] 2019-09-30 12:23
@sebastianbochan I'm using the 33 SDK expo version that uses `React Native 0.59.8`.

Maybe will be a great solution.

**Comment by ms042087** [comment] 2019-09-30 13:39
Hi everyone @Jessica7  @leonascimento  @leonascimento  @sebastianbochan , could you please try the below HighchartsReactNative.js?
I am using React native 0.59.1. 
https://github.com/ms042087/tonyho/blob/master/HighchartsReactNative.js

**Comment by sebastianbochan** [comment] 2019-09-30 13:41
This version uses not up-to-date webview pack. So after update you will have an error with incorrect packages.

**Comment by ms042087** [comment] 2019-09-30 13:58
@sebastianbochan 
`import React from 'react';
import {
    Text,
    View,
    Dimensions,
    StyleSheet,
    Platform
} from 'react-native';
import { WebView } from 'react-native-webview';`

Work for me as well.
![1](https://user-images.githubusercontent.com/19402657/65885536-6c858000-e3cd-11e9-956c-8f26c8ed4e6b.png)

**Comment by sebastianbochan** [comment] 2019-10-01 09:44
Are you able to post me your `package.json`?

**Comment by jayanth1234** [comment] 2019-10-01 10:04
Can some one please post the render code of the above output..? Since I am getting the HTML code or snippet in the emulator or mobile. Thanks!! in advance

**Comment by sebastianbochan** [comment] 2019-10-01 13:58
@jayanth1234, @ms042087, @leonascimento, @Jessica7 

I pushed new version which allows you also load files from CDN (set param `useCDN={true}`). All is commented in App.js.

Hope that all tests will pass.

Regarding error with non-parsing HTML, its related with mode (I guess, correct me if Im wrong) and known bugs in `react-native-webview` (See mentioned refs in one of my previous posts).

Unfortunately its not strictly related with wrapper.

**Comment by BabishanM** [comment] 2019-10-04 08:40
Hi @sebastianbochan 
I am using react-naive 0.60 and it is not working for me, I am getting blank screen

**Comment by athenawisdoms** [comment] 2019-10-05 17:39
What is the proper way to install the `beta-webview` branch in a fresh project? 

Tried `npm install --save highcharts/highcharts-react-native#beta-webview` but getting the error 

```
node:43440) UnhandledPromiseRejectionWarning: Error: jest-haste-map: Haste module naming collision:
  Duplicate module name: react-native
  Paths: /Users/x/foo/node_modules/react-native/package.json collides with /Users/x/foo/node_modules/highcharts-react-native/node_modules/react-native/package.json
```

`package.json` shows I am using `expo` 34.0.4 and `react-native` from `https://github.com/expo/react-native/archive/sdk-33.0.0.tar.gz`

**Comment by sebastianbochan** [comment] 2019-10-07 12:23
@BabishanM,
Unfortunately I was not able to reproduce the problem, which android do you have? 

@athenawisdoms 
I did not publish it in npm, so at this moment I recommend to download `beta-webview`, and use package by import HighchartsReactNative from `path/to/the/beta-webview`

**Comment by sebastianbochan** [comment] 2019-10-17 13:38
Regarding to update, in the wrapper I used webkit.postmessage and event to cache it. At this moment it was removed from webview and is still developed / reorganized.

Ref:
- https://github.com/react-native-community/react-native-webview/issues/809

**Comment by IgorUsoltsev** [comment] 2019-11-18 12:55
Had the issue with Expo + RN High Charts as well. 

And the case was ONLY with published project. 

The reason was really funny enough. 

https://github.com/highcharts/highcharts-react-native/blob/beta-webview/dist/src/HighchartsReactNative.js#L12 - here guys you use HTTP. As I suppose in the latest versions of iOS Apple could have blocked non secure connections in iFrames (i.e. WebViews). So I just changed it to HTTPS:
`const cdnPath = 'https://code.highcharts.com/';` and it worked!

Please give some time to Expo so cache could go on. Hope that will help you!

**Comment by sebastianbochan** [comment] 2019-11-19 09:20
Thank you for the feedback!

**Comment by sebastianbochan** [comment] 2019-11-25 12:38
The new version (2.0.2) has been already released.

Im closing the ticket, but please reopen if any issues will come again.

**Closed by sebastianbochan** 2019-11-25 12:38 UTC
Labels: pending reply

**Comment by bestjsguru** [comment] 2019-11-27 01:55
Hi @sebastianbochan 
I love the react native and I am very interested in your highchart component.
So I am going to use it on my react native project but it shows only empty background
react-native: 0.61
react: 16.9
npm: 6.12.1
node: 12.13.1
@highchart/highcharts-react-native: 2.0.2

I tried to use react-native 0.59 for this component but had same problem
used 1.0.0 version on RN 0.59

**Comment by sebastianbochan** [comment] 2019-11-28 14:15
Will check that and get back to you after tests.

**Comment by sebastianbochan** [comment] 2019-12-03 13:21
@bestjsguru did you run this in Android or iOS? Which version of OS?

**Comment by fattomhk** [comment] 2019-12-04 09:35
@sebastianbochan 
I've init a new rn project with the following package.json
```{
  "name": "highcharts",
  "version": "0.0.1",
  "private": true,
  "scripts": {
    "android": "react-native run-android",
    "ios": "react-native run-ios",
    "start": "react-native start",
    "test": "jest",
    "lint": "eslint ."
  },
  "dependencies": {
    "@highcharts/highcharts-react-native": "^2.0.2",
    "react": "16.9.0",
    "react-native": "0.61.5",
    "react-native-webview": "^7.5.2"
  },
  "devDependencies": {
    "@babel/core": "^7.7.4",
    "@babel/runtime": "^7.7.4",
    "@react-native-community/eslint-config": "^0.0.5",
    "babel-jest": "^24.9.0",
    "eslint": "^6.7.2",
    "jest": "^24.9.0",
    "metro-react-native-babel-preset": "^0.57.0",
    "react-test-renderer": "16.9.0"
  },
  "jest": {
    "preset": "react-native"
  }
}
```
Then I receive some error messages in terminal:
```
Error: 'node_modules/@highcharts/highcharts-react-native/highcharts-files/highcharts.js' cannot be loaded as its extension is not registered in assetExts
```

After that, I added 'css', 'js to metro as following:
```
/**
 * Metro configuration for React Native
 * https://github.com/facebook/react-native
 *
 * @format
 */

const { getDefaultConfig } = require('metro-config')


module.exports = (async () => {
  const {
      resolver: { assetExts },
  } = await getDefaultConfig()
  console.log(assetExts)
  return {
      transformer: {
          getTransformOptions: async () => ({
              transform: {
                  experimentalImportSupport: false,
                  inlineRequires: false,
              },
          }),
      },
      resolver: {
          assetExts: [...assetExts, 'css', 'js'],
      },
  }
})()
```

Finally I got this:
![image](https://user-images.githubusercontent.com/1083049/70130823-38278c00-16bc-11ea-80b8-f78a759f4862.png)

Am I missing any installation step?

**Comment by mrinal-roy-au2** [comment] 2020-02-19 12:03
I am getting this error:
`**Encountered an error loading page {"canGoBack": false, "canGoForward": false, "code": -1, "description": "net::ERR_FILE_NOT_FOUND", "loading": false, "target": 18623, "title": "", "url": "file:///android_asset/highcharts-layout/index.html"}**`

I am running RN 0.61.5 with android emulator. Please tell me which files to add and where?

**Comment by oillada** [comment] 2020-02-19 17:46
Same issues here, any help?

**Comment by georgeCts** [comment] 2020-02-19 22:40
> I am getting this error:
> `**Encountered an error loading page {"canGoBack": false, "canGoForward": false, "code": -1, "description": "net::ERR_FILE_NOT_FOUND", "loading": false, "target": 18623, "title": "", "url": "file:///android_asset/highcharts-layout/index.html"}**`
> 
> I am running RN 0.61.5 with android emulator. Please tell me which files to add and where?

Same issue :(

**Comment by NRamirezCR** [comment] 2020-02-19 22:43
> @sebastianbochan Android 9.0, compiler compileSdkVersion = 28
> 
> Finally get it done.
> 
> Blank page or page showing html text are basically due to wrong path or Android debug mode problem. I tried to put a website URL into source, it displayed normally. Therefore, the WebView module should work fine.
> 
> Main Problem:
> I think it is not possible to put local html file into WebView source in Android debug mode.
> Also, the source for WebView uses `require()` which I think it is for IOS. `uri:...` should be used for Android. Using `require()` gives blank page and using `uri:...` gives html text in Android virtual device.
> 
> My Solution:
> 
> 1. Change the source to
>    `source = {(Platform.OS == 'ios') ? require('../highcharts-layout/index.html') : { uri: 'file:///android_asset/highcharts-layout/index.html' }}`
> 
> This changes the source path of the local files based on the platforms.
> Remember to import 'Platform' from 'react native'
> 
> 1. Put the files (i.e. Folder: `highcharts-layout` and `highcharts-files`) to `android/app/src/main/assets` and `/ios`
> 2. Use release mode instead of debug mode
>    i.e. run `react-native run-android --variant=release`
> 
> Hope it helps.

This worked for me! Thanks!

**Comment by mustapha-khan** [comment] 2020-03-13 07:25
i am having similar issue on  using highchart in EXPO application . 
getting the error on running app on emulator or physical device : ERR_FILE_NOT_FOUND

![image](https://user-images.githubusercontent.com/49139623/76598227-3cb5d900-6524-11ea-99fd-fa86021280b0.png)

the issue seems to be in the source provided to webView in highcharts react native wrapper . i.e:
source={highchartsLayout}

I solved it by using  expo-asset-utils to convert my required file into asset in componentdidmount() and used the uri of this asset as source of webView so that my modified HighchartsReactNative.js file looks like : 


`
async componentDidMount() {
        // catch rotation event
        try {
            const asset = await  AssetUtils.resolveAsync(require('../highcharts-layout/index.html'));
            // console.log({ asset });
            this.setState({ asset });
            console.log("=- -= CHEK ASSET -= = ", asset)
          } catch (error) {
            console.log({ error });
          }
        Dimensions.addEventListener('change', this.onRotate);
    }
`

and in webview using source as  : 

`
                source={{uri:this.state.asset.localUri}}
`

using the uri of asset didn't work for me hence using loacalUri

**Comment by mustapha-khan** [comment] 2020-03-13 07:33
> > I am getting this error:
> > `**Encountered an error loading page {"canGoBack": false, "canGoForward": false, "code": -1, "description": "net::ERR_FILE_NOT_FOUND", "loading": false, "target": 18623, "title": "", "url": "file:///android_asset/highcharts-layout/index.html"}**`
> > I am running RN 0.61.5 with android emulator. Please tell me which files to add and where?
> 
> Same issue :(

i am having similar issue on  using highchart in EXPO application . 
getting the error on running app on emulator or physical device : ERR_FILE_NOT_FOUND

![image](https://user-images.githubusercontent.com/49139623/76598227-3cb5d900-6524-11ea-99fd-fa86021280b0.png)

the issue seems to be in the source provided to webView in highcharts react native wrapper . i.e:
source={highchartsLayout}

I solved it by using  expo-asset-utils to convert my required file into asset in componentdidmount() and used the uri of this asset as source of webView so that my modified HighchartsReactNative.js file looks like : 


`async componentDidMount() {`
    `       try {`
           ` const asset = await  AssetUtils.resolveAsync(require('../highcharts-layout/index.html'));`
`            this.setState({ asset });`
 `           console.log("=- -= CHEK ASSET -= = ", asset)`
 `         } catch (error) {`
  `          console.log({ error });`
`          }`
`        Dimensions.addEventListener('change', this.onRotate);`
`    }`

and in webview using source as  : 

`
                source={{uri:this.state.asset.localUri}}
`

using the uri of asset didn't work for me hence using loacalUri

 try this and it might help you

**Comment by sebastianbochan** [comment] 2020-03-13 11:41
Thank you for the suggestion.

**Comment by sebastianbochan** [comment] 2020-03-18 14:41
@mustapha-khan could you share your simplified working project? When I run the Expo SDK 64, was not able to run it properly in Android.

**Comment by fattomhk** [comment] 2020-03-19 08:04
> @sebastianbochan
> I've init a new rn project with the following package.json
> 
> ```
>   "name": "highcharts",
>   "version": "0.0.1",
>   "private": true,
>   "scripts": {
>     "android": "react-native run-android",
>     "ios": "react-native run-ios",
>     "start": "react-native start",
>     "test": "jest",
>     "lint": "eslint ."
>   },
>   "dependencies": {
>     "@highcharts/highcharts-react-native": "^2.0.2",
>     "react": "16.9.0",
>     "react-native": "0.61.5",
>     "react-native-webview": "^7.5.2"
>   },
>   "devDependencies": {
>     "@babel/core": "^7.7.4",
>     "@babel/runtime": "^7.7.4",
>     "@react-native-community/eslint-config": "^0.0.5",
>     "babel-jest": "^24.9.0",
>     "eslint": "^6.7.2",
>     "jest": "^24.9.0",
>     "metro-react-native-babel-preset": "^0.57.0",
>     "react-test-renderer": "16.9.0"
>   },
>   "jest": {
>     "preset": "react-native"
>   }
> }
> ```
> 
> Then I receive some error messages in terminal:
> 
> ```
> Error: 'node_modules/@highcharts/highcharts-react-native/highcharts-files/highcharts.js' cannot be loaded as its extension is not registered in assetExts
> ```
> 
> After that, I added 'css', 'js to metro as following:
> 
> ```
> /**
>  * Metro configuration for React Native
>  * https://github.com/facebook/react-native
>  *
>  * @format
>  */
> 
> const { getDefaultConfig } = require('metro-config')
> 
> 
> module.exports = (async () => {
>   const {
>       resolver: { assetExts },
>   } = await getDefaultConfig()
>   console.log(assetExts)
>   return {
>       transformer: {
>           getTransformOptions: async () => ({
>               transform: {
>                   experimentalImportSupport: false,
>                   inlineRequires: false,
>               },
>           }),
>       },
>       resolver: {
>           assetExts: [...assetExts, 'css', 'js'],
>       },
>   }
> })()
> ```
> 
> Finally I got this:
> ![image](https://user-images.githubusercontent.com/1083049/70130823-38278c00-16bc-11ea-80b8-f78a759f4862.png)
> 
> Am I missing any installation step?

I get it work after changing the metro config file into

```
module.exports = (async () => {
  const {
      resolver: { sourceExts, assetExts },
  } = await getDefaultConfig()
  return {
      transformer: {
          getTransformOptions: async () => ({
              transform: {
                  experimentalImportSupport: false,
                  inlineRequires: false,
              },
          }),
      },
      resolver: {
        sourceExts,
        assetExts: [...assetExts, 'css'],
      },
  }
})()
```

**Comment by sebastianbochan** [comment] 2020-03-19 09:46
Big thanks for the hint. Will share it with our users to be ensure that it worked.

**Comment by ChenRaul** [comment] 2020-05-20 07:20
@sebastianbochan Except for yours Highcharts, actually, that's what you're talking about with using react-native-webview,when the html file import other JS files which will hint xxxx.js cannot be loaded as its extension is not registered in assetExts.And I use yours approach,but it didn't work.
So  do you have any other solutions? thanks.

 **Environment**
OS: iPhone
OS version:
"react": "16.11.0",
"react-native": "0.62.2",
react-native-webview : 8.0.0;

**Comment by samimhakimi** [comment] 2020-07-09 09:07
> platforms

How to implement this could you please explain it?

**Comment by sebastianbochan** [comment] 2020-07-15 07:32
We are wokring on that and debugging the problem. Can be related with new versions of modules.

Thankfully, we are able to reproduce the problem.

I will inform you about progress, when find a reason of issue.

**Comment by walidbezzaoui** [comment] 2020-10-19 19:01
any progress on this ?

**Comment by fattomhk** [comment] 2020-10-20 02:33
> any progress on this ?

3.0 fixed this issue. But 3.0 got another problem with iOS, here is the [hotfix].(https://github.com/highcharts/highcharts-react-native/issues/104#issuecomment-708394718).

**Comment by ManelGonzalez-ops** [comment] 2020-12-07 17:23
There's not even a working example on the internet with this thing working... hilarious

**Comment by DamanSoftRadixx** [comment] 2023-09-28 10:12
If any one try to Implement HIChartView in flutter with native code with the help of ( implement class with PlatformView) in flutter . Then make sure during make instance of HIChartView give them layout and background color to HIChartView if background color missing then view not rendered and it will not showing error in log .
