### ISSUE TITLE
[Error] Element ref was specified as a string but no owner was set.

### ISSUE THREAD

**Issue by kdenz** [highcharts/highcharts-react-native#61] opened 2020-04-01 05:29 UTC
![image](https://user-images.githubusercontent.com/12795428/78102244-763f7d00-741c-11ea-8248-2787a695f48d.png)

RN 0.61.5
react 16.9
react-native-webview v8

I had to change `ref="webview"` in `HighchartsReactNative.js` to `ref = {(ref)=>{this.webview = ref}}` in order to fix the error

**Comment by sebastianbochan** [comment] 2020-04-01 09:54
Hi @kdenz,
Thank you for reporting (and solution in PR), but would like to know how you do that? When I run my demo in Expo or RN I was not able to reproduce it.

**Comment by kdenz** [comment] 2020-04-01 10:48
@sebastianbochan hi there, have you tried running it on RN0.61.5 + react-native-webview 8.xx + iOS 13.4 ? Somehow this error popped up for me

**Comment by sebastianbochan** [comment] 2020-04-01 12:34
Will test it (I have older RN) and wait for feedback from other users. I would like to be sure that its not break other implementions.

**Comment by sebastianbochan** [comment] 2020-08-03 11:59
The new 3.0 version is released. 

Im closing this ticket. If you will encounter any problems, please create a new ticket. In this case we will avoid confusing and keep the newest version on track.

**Closed by sebastianbochan** 2020-08-03 11:59 UTC
