### ISSUE TITLE
Error loading page Domain :undefined Error Code:-1 Description:net::ERR_FILE_NOT_FOUND

### ISSUE THREAD

**Issue by 112200369** [highcharts/highcharts-react-native#65] opened 2020-04-02 02:38 UTC
After the introduction of highcharts component according to the official package introduction of highcharts react native, I did not display the expected chart report in my project, Seek help mogul！
### Error loading page Domain :undefined Error Code:-1 Description:net::ERR_FILE_NOT_FOUND

**Comment by sebastianbochan** [comment] 2020-04-02 08:43
Closing as duplicate of https://github.com/highcharts/highcharts-react-native/issues/51

**Closed by sebastianbochan** 2020-04-02 08:43 UTC

**Comment by sanjeetCoder** [comment] 2020-10-19 09:07
If you are trying to run reactJs into react native webview then run the below command for reactJs 

---npm run build
---npm install serve
---npx serve -s build

ReactJs Code
-------------------------------------

import React from 'react';
import './App.css'
const App = () => {
   return (
      <div className="App">
              <h1>Hello World</h1>
        </div>
      )
   };

   export default App

It will show something

 Serving!                                      │
   │                                                 │
   │   - Local:            http://localhost:5000     │
   │   - On Your Network:  http://192.168.2.3:5000   │
   │                                                 │
   │   Copied local address to clipboard!            │
   │

Use  http://localhost:5000 into the browser 
http://192.168.2.3:5000   in  React Native -webview   



React Native Code 
------------------------------------------------------------------------------------
import React from "react";
import { WebView } from "react-native-webview";

const App= () => {
  return (
        <WebView 
          
        originWhitelist={['*']}
        source={{ uri:" http://192.168.2.3:5000"}}
        javaScriptEnabled={true}
        domStorageEnabled={true}
        useWebKit={true}
        startInLoadingState={true}
        />
        
  );
};

export default App;

For react-native use only npm start in another terminal in project directory


--------------Hope It will help -----------------
