### ISSUE TITLE
Using extracted react-native-webview instead of the webview in RN core

### ISSUE THREAD

**Issue by SaeedZhiany** [highcharts/highcharts-react-native#8] opened 2019-07-23 05:57 UTC
Currently, this library is using the RN core's `webview` component that causes a warning message at runtime.

![Screenshot_1563861438](https://user-images.githubusercontent.com/13766432/61686305-77b89180-ad34-11e9-8fd3-1f78260e6500.png)

**Comment by barunprasad** [comment] 2019-08-01 16:39
This would throw an error with RN 0.60.x.
<img width="390" alt="Screen Shot 2019-08-01 at 10 08 25 PM" src="https://user-images.githubusercontent.com/5308666/62311200-f20db200-b4a8-11e9-96bb-7f0fcba6d967.png">

**Comment by sebastianbochan** [comment] 2019-08-02 09:51
Hi,
Thank you for reporting about the problem. I will fix it as soon as possible.

**Comment by bartvanduinkerken** [comment] 2019-08-12 11:28
Hi, 
Any timeline on this fix?

**Comment by sebastianbochan** [comment] 2019-08-14 09:49
Hi @bartvanduinkerken,
At this moment we do not have ETA for it, but will try to update next week.

**Comment by bartvanduinkerken** [comment] 2019-08-14 09:50
Hi @sebastianbochan 
That would be great :) thank you for your time

**Comment by SachinSharma2018** [comment] 2019-08-28 09:44
@sebastianbochan Any update in this because of this, we are not able to use this library.

**Comment by SchwSimon** [comment] 2019-08-28 10:34
@sebastianbochan Same here, we need this update please.

**Comment by mukeshsharma1201** [comment] 2019-08-29 10:47
> This would throw an error with RN 0.60.x.
> <img alt="Screen Shot 2019-08-01 at 10 08 25 PM" width="390" src="https://user-images.githubusercontent.com/5308666/62311200-f20db200-b4a8-11e9-96bb-7f0fcba6d967.png">

Facing this same issue.

**Comment by sebastianbochan** [comment] 2019-08-29 11:35
Hi,
Im still working on this, but came across a few problems, so need some extra time. 

Thank you for your patience.

**Comment by SchwSimon** [comment] 2019-08-30 09:46
@sebastianbochan
Yes, that's all we need.
As stated here [facebook.github.io/react-native/docs/webview](https://facebook.github.io/react-native/docs/webview) 
You just need to add this package [github.com/react-native-community/react-native-webview](https://github.com/react-native-community/react-native-webview)
And use the WebView component from this package instead of rn.

Could you push this small update to master please?

**Comment by sebastianbochan** [comment] 2019-08-30 10:26
Yes yes I agree, this package is included.

This update is breaking-change, so I would preferer wait for extra feedback from other users.

**Comment by mukeshsharma1201** [comment] 2019-08-30 12:29
Idk maybe I was not able to install it correctly?<br>I am getting   `Error: 'dist/highcharts-files/highcharts.js' cannot be loaded as its extension is not registered in assetExts`<br>
`::1 - - [30/Aug/2019:12:22:28 +0000] "GET /assets/dist/highcharts-files/highcharts.js HTTP/1.1" 404 - "http://localhost:8081/assets/dist/src/index.html?platform=ios&hash=43e650e85e6de95a8ff51b327c36d25d" "Mozilla/5.0 (iPhone; CPU iPhone OS 12_4 like Mac OS X) AppleWebKit/605.1.15 (KHTML, like Gecko) Mobile/15E148"`

**Comment by SchwSimon** [comment] 2019-08-30 13:09
@sebastianbochan could you please create a branch for this instead of sharing a file?

**Comment by mukeshsharma1201** [comment] 2019-09-04 10:45
@sebastianbochan  I have tried using local minified js files with react-native-webview with no luck. This wrapper is much needed. Can you please update on this issue?

**Comment by sebastianbochan** [comment] 2019-09-04 12:52
I prepared a beta-release candidate.

Please test the demo, created on separate branch: https://github.com/highcharts/highcharts-react-native/tree/beta-webview

Any feedback will be helpful.

**Comment by SchwSimon** [comment] 2019-09-04 14:44
@sebastianbochan Can you fix these 2 errors in your package.json file please.

```
"errors": [
    "Missing required field: name",
    "Missing required field: version"
]
```

**Comment by sebastianbochan** [comment] 2019-09-04 14:51
```
{
  "main": "node_modules/expo/AppEntry.js",
  "name": "@highcharts/highcharts-react-native",
  "version": "1.0.0",
  "license": "SEE LICENSE IN <LICENSE>",
  "repository": {
    "type": "git",
    "url": "git+https://github.com/highcharts/highcharts-react-native-official.git"
  },
  "keywords": [
    "highcharts",
    "highstock",
    "highmaps",
    "react-native"
  ],
  "devDependencies": {
    "eslint": "^5.16.0",
    "eslint-plugin-react": "^7.12.4",
    "react": "^16.4.0",
    "react-addons-test-utils": "^15.6.2",
    "react-dom": "^16.4.0",
    "react-test-renderer": "^16.4.0",
    "react-unit": "^3.0.0"
  },
  "errors": [
    "Missing required field: name",
    "Missing required field: version"
  ]
}
```

will be correct?

**Comment by SchwSimon** [comment] 2019-09-04 16:03
@sebastianbochan you can remove the "errors" prop, this was just a list of the package.json errors.
So basically "name" and "version" props were missing.

You can also validate your packaje.json file here: http://package-json-validator.com

**Comment by sebastianbochan** [comment] 2019-09-04 16:54
@SchwSimon,
My mistake, I verified the `package.json` from other branch. 

I added missing fields to the new package.json by commit: https://github.com/highcharts/highcharts-react-native/commit/16767eaed47cc0e212a48a0eacfa5a2a3b78a313

**Comment by SchwSimon** [comment] 2019-09-05 10:29
@sebastianbochan Thank you, I just tested the branch, I can't bundle anymore.

```
jest-haste-map: Haste module naming collision: react-native
  The following files share their name; please adjust your hasteImpl:
    * <rootDir>\node_modules\react-native\package.json
    * <rootDir>\node_modules\expo\node_modules\react-native\package.json
```

**Comment by sebastianbochan** [comment] 2019-09-06 08:39
@SchwSimon,
The main repo is demo expo application, but if you need only `Highcharts-react-native` package, you should clone only the `dist` folder and then call `npm install` or `yarn`.

**Comment by SchwSimon** [comment] 2019-09-06 12:31
@sebastianbochan Could you create another branch for the ones not using Expo, so we can properly install the package?

Also note that even in the /dist package, the entry point `main` still refers to expo `"main": "node_modules/expo/AppEntry.js"`

**Comment by sebastianbochan** [comment] 2019-09-06 13:50
@SchwSimon 
Done https://github.com/highcharts/highcharts-react-native/tree/dist-branch

**Comment by SchwSimon** [comment] 2019-09-06 20:32
@sebastianbochan Thank you very much.
Ok so the package installation and bundling is working fine now.
But there is a TypeError, I am using the most basic example:
```
<HighchartsReactNative
    styles={{}}
    options={{
        series: [{
            data: [1, 2, 3]
        }]
    }} />
```
![grafik](https://user-images.githubusercontent.com/9978486/64458645-2ef74500-d0f6-11e9-8b82-ccf3958410fa.png)

**Comment by sebastianbochan** [comment] 2019-09-09 11:44
@SchwSimon,
Well I was not able to reproduce this error, any ideas how can I do that?

**Comment by SchwSimon** [comment] 2019-09-10 13:35
@sebastianbochan 
I think it may be due to your node reference.
On mount you try to access `this.webView` which does not exist as you try to get the WebView ref by `ref={this._webViewRef}`

**Comment by sebastianbochan** [comment] 2019-09-11 12:49
@SchwSimon,
Will check that, meantime Im working on full-compatiblity with android https://github.com/highcharts/highcharts-react-native/issues/4

**Comment by markcrockett** [comment] 2019-09-12 01:59
@sebastianbochan also experiencing this.webView is undefined in DidMount.

this.webView.postMessage(
            this.serialize(this.props.options, true)
        );

I was able to reproduce by updating chart config stored in state.

**Comment by wzhang2** [comment] 2019-09-13 09:43
do we have an ETA for the fix?

**Comment by KacperMadej** [comment] 2019-09-19 10:33
Hi @wzhang2 
We do not have ETA for the fix at this moment.
Our main wrapper developer is our of the office and will be back in October - he might have more detail for the case.

**Comment by sebastianbochan** [comment] 2019-09-26 14:08
Im getting back to working on it, hope that tomorrow have a fix for mentioned issues.

**Comment by BabishanM** [comment] 2019-09-27 11:19
@sebastianbochan Hi I am facing the same issue 


`"@highcharts/highcharts-react-native": "^1.0.0",
"react": "16.8.6",
"react-native": "0.60.5",
"react-native-webview": "^7.1.0",`

When i tried the same with the provided beta-webview branch

i am getting the below issue
![Screenshot 2019-09-27 at 4 48 15 PM](https://user-images.githubusercontent.com/33688844/65765718-a729b700-e146-11e9-8e45-cb16b0a50791.png)

Can you please assist on the same

**Comment by sebastianbochan** [comment] 2019-09-27 13:05
Hi @BabishanM ,
Thank you for really big feedback and advices. I committed your suggestions on my `beta-webview` branch.

Will be really grateful if you will be able to test it too.

ps. Im waiting for final feedback about Android before final release. (case #4)

**Comment by BabishanM** [comment] 2019-09-28 07:31
Hi @sebastianbochan 

Thank you for your time to fix this.
Can you let us know when will this be reflecting in master? Like an ETA?

Again thank you.

**Comment by sebastianbochan** [comment] 2019-09-28 08:05
Hi @BabishanM,
On Monday I will ad CDN support and multiple modules, then prepare final beta-release. If all will be correct, I hope that 1 or 2.10 will publish official 2.0 version.

**Comment by BabishanM** [comment] 2019-09-28 14:19
Hi @sebastianbochan  

It is not working as expected, I am getting blank screen.
I have mentioned about it in issue #4 
Did i miss something?

**Comment by SchwSimon** [comment] 2019-09-30 10:52
@sebastianbochan 
With your next push, could you also please push a new version to the `dist-branch`.
Thank you.

**Comment by sebastianbochan** [comment] 2019-09-30 11:45
Yes sure

**Comment by sebastianbochan** [comment] 2019-10-01 14:00
@SchwSimon 
I did it.

Meantiime I also publish new beta-version which supports loading multiple files from file system or CDN (set param `useCDN={true}`). All is commented in App.js.

Hope that all tests will pass.

Let me know if you came across any problems.

**Comment by leonascimento** [comment] 2019-10-02 02:03
@sebastianbochan this is not working yet.

Just a little observation question. Do we need to use` https` here?

https://github.com/highcharts/highcharts-react-native/commit/64eb2814f81c784a48fad5ff91c74f96f4e03b25#diff-0db2095e1ba25d92a152d80a7f75a71fR12

I saw the CDNs links on this page using `https`.
http://code.highcharts.com/

**Comment by sebastianbochan** [comment] 2019-10-02 12:27
Hi @leonascimento,
Https is not correct supported in this solution, so at this moment the only way (which I found) was skip SSL.

Could you elaborate what kind of errors you have? Still html is printed as string ? If yes, did you check this issue:
- https://github.com/react-native-community/react-native-webview/issues/428

**Comment by SchwSimon** [comment] 2019-10-02 14:51
@sebastianbochan I get a bundling error because you added entry point ("main") in the package.json.

It works when I remove it.

Also the component renders this:
![grafik](https://user-images.githubusercontent.com/9978486/66054765-c6ed2080-e534-11e9-999b-22b9781c8d82.png)

**Comment by leonascimento** [comment] 2019-10-03 00:04
@sebastianbochan yes, I'm seeing just HTML printed as a string.
Thank about this link. I will try to import following the tips of this issue.

**Comment by sebastianbochan** [comment] 2019-10-03 13:16
So lets wait for the further feedback until tomorrow or end of this week. If all will be fine, I will merge with the current master.

**Comment by taehajoo** [comment] 2019-10-04 18:07
I am using the beta webview branch and it has solved my blank screen issue. I am having no problems with it. I hope this gets merged to master soon.

**Comment by sebastianbochan** [comment] 2019-10-07 12:20
@taehajoo ios or android?

**Comment by taehajoo** [comment] 2019-10-07 17:08
@sebastianbochan 
Just iOS simulator via Expo. I was getting a blank white screen before using master branch but beta-webview branch fixes the issue.

**Comment by sebastianbochan** [comment] 2019-10-08 12:43
The master-branch is broken, so just looking for good solution, but always is the same problem, that it works in a few scenarios and does not work also in a few.

**Comment by mukeshsharma1201** [comment] 2019-10-16 07:51
Any updates on this issue? Can you please merge this in master?

**Comment by SchwSimon** [comment] 2019-10-17 13:29
@sebastianbochan We also really need this, clients are waiting and paying for this service without being able to use it because of the issue.

**Comment by sebastianbochan** [comment] 2019-10-17 13:39
Regarding to update, in the wrapper I used webkit.postmessage and event to cache it. At this moment it was removed from webview and is still developed / reorganized.

Ref:
- https://github.com/react-native-community/react-native-webview/issues/809

@SchwSimon @mukeshsharma1201 

I can merge it but updates will be broken. Is it fine for you?

**Comment by SchwSimon** [comment] 2019-10-19 10:02
@sebastianbochan you can use the new `postMessage` function.

`window.ReactNativeWebView.postMessage(data);`
Source: `https://github.com/react-native-community/react-native-webview/releases/tag/v5.0.0`

**Comment by sebastianbochan** [comment] 2019-10-22 13:09
Will check that, I had a few problems with that, but found a little bit different workaround.

**Comment by antonkashpor** [comment] 2019-10-23 15:51
@sebastianbochan does it mean on iOS it doesn't work at all? 
Thanks

**Comment by sebastianbochan** [comment] 2019-10-24 10:09
@antonkashpor @taehajoo @leonascimento 
Good news, I was able to find a solution to communicate between webview and app. 

The newest wrapper is available on `beta-webview` branch.

@SamHoulder committed changes also into `dist branch`.

Just waiting for the feedback, hope that will work properly ;)

**Comment by SchwSimon** [comment] 2019-10-25 15:52
Thanks @sebastianbochan 

So now there still is this: https://github.com/highcharts/highcharts-react-native/issues/8#issuecomment-537530226

Referring to the `dist-branch`
1) "main" in the package.json
2) Error loading page (see image from the comment link above)

**Comment by spoorthy25** [comment] 2019-10-30 06:18
@sebastianbochan : Is there any update on issue "WebView has been removed from React Native. It can now be installed and imported from 'react-native-webview' instead of 'react-native'

<img width="784" alt="Screenshot 2019-10-30 at 2 15 56 PM" src="https://user-images.githubusercontent.com/27670557/67833618-1c125700-fb20-11e9-9bdd-0730c04b1acf.png">
 "

**Comment by sebastianbochan** [comment] 2019-10-30 10:05
@spoorthy25,
Please check our discussion above about the webview and test the `beta` version which is also available as the branch.

At this moment we are in testing stage and when the feedback will be posiitive, then I will merge meta into master official release.

**Comment by slaci** [comment] 2019-11-01 12:27
I tried both the `beta-webview` and `dist-branch` branches on windows + android 10 emulator with react native `0.61.3`, but sadly it doesn't work out of the box.

1. In the [package.json](https://github.com/highcharts/highcharts-react-native/blob/beta-webview/dist/package.json#L2) I have to remove the `main` key, otherwise I get an error, like @SchwSimon  mentioned
2. The next step is to install the webview plugin: `yarn add react-native-webview`
3. In the [source code](https://github.com/highcharts/highcharts-react-native/blob/beta-webview/dist/src/HighchartsReactNative.js#L14) the html file for the webview is required from `file:///android_asset` so I had to copy the `highcharts-layout` and `highcharts-files` folders to `android/app/src/main/assets` folder. I haven't seen this mentioned anywhere, but I think this is totally required.
4. Now the sample code should work, but instead of that I get an empty screen. If I change the index.html and rebuild, then the dummy text appears, so the webview loads for sure. But the JS can't load the highcharts lib from the `highcharts-files` folder (theres no error, just blank screen).

My hackish solution was to copy `highcharts.js` from `highcharts-files` folder next to `index.html`, then put `<script src="highcharts.js" />` into the html. Then in the wrapper's js I changed the `runFirst` variable's content to only `Highcharts.chart("container", ${this.serialize(this.props.options)});` and this way the chart works!

So Im pretty sure the [dynamic loading of highchart](https://github.com/highcharts/highcharts-react-native/blob/beta-webview/dist/src/HighchartsReactNative.js#L79) with xhr fails, but I don't know how to debug this, webkit doesn't show any errors, just silently fails.

**Comment by sebastianbochan** [comment] 2019-11-04 09:50
Hi @slaci,
Regarding to Android, it looks like the issue know form the other thread: https://github.com/highcharts/highcharts-react-native/issues/4. Could you confirm?

**Comment by slaci** [comment] 2019-11-05 12:55
Not sure about that thread, very long and messy.

Webview has a prop called `allowFileAccessFromFileURLs` which seems to be a solution for me. If I put `allowFileAccessFromFileURLs={true}` into `HighchartsReactNative.js`'s WebView (it already has `allowFileAccess`, but thats not enought), then the sample highcharts code works for me on android (still need to do the 3 points I mentioned before). The same setup: Pixel Xl 3 Android 10 emulator, react native 0.61.3 without expo.

On ios I get the `assetExts` error mentioned here: https://github.com/highcharts/highcharts-react-native/issues/8#issuecomment-526582952
WebView cannot load the css and js files from the hmtl file because of this. Not sure if its something to do with the metro bundler (that has an assetExts option) or with the WebView or something else...

**Comment by SchwSimon** [comment] 2019-11-14 11:52
@sebastianbochan any updates on when master branch will be updated?

**Comment by slaci** [comment] 2019-11-15 08:44
This branch only works on android if you add the `allowFileAccessFromFileURLs` prop to the webview, but on ios that doesn't help im afraid.

The only way I could make it to work on ios was to inline the highcharts.js (+ modules if needed) and the style.css into the index.html. And my `runFirst` variable contains only this: `Highcharts.chart("container", ${this.serialize(this.props.options)}); true;` in the `HighchartsReactNative.js`. If you dont have `true;` at the end, then ios will show a warning... `return true;` does not work, just this `true;`...

Fusion chart react native wrapper does something similar. They have a build script which inlines the assets automatically on build, maybe worth a look: https://github.com/fusioncharts/react-native-fusioncharts.

**Comment by sebastianbochan** [comment] 2019-11-18 10:14
Hi,
So I will add the `allowFileAccessFromFileURLs` param too. Update docs and release the current master branch this week.

**Comment by benidel** [comment] 2019-11-21 08:58
Hi @sebastianbochan,
I hope you're doing great ! is there any news about the update ? I'm using the library for an ilmportant project and need to know if I should wait for a resolution or find another lib or way to display the charts ?

Kinds :)

**Comment by sebastianbochan** [comment] 2019-11-21 09:25
I will release new version (currently as beta) tomorrow morning.

**Comment by sebastianbochan** [comment] 2019-11-25 12:38
The new version (2.0.2) has been already released.

Im closing the ticket, but please reopen if any issues will come again.

**Closed by sebastianbochan** 2019-11-25 12:38 UTC

**Comment by SchwSimon** [comment] 2019-11-25 13:06
@sebastianbochan The `Error loading page` still occurs.

![grafik](https://user-images.githubusercontent.com/9978486/69542814-7f12d480-0f8c-11ea-8acc-730b9fac83f4.png)

I use the most basic setup
```
<HighchartsReactNative
    styles={{}}
    options={{
        series: [{
            data: [1, 2, 3]
        }]
    }} />
```

**Comment by sebastianbochan** [comment] 2019-11-25 13:10
Have you tried move files like I described in Readme?

**Comment by kot7kz** [comment] 2019-11-26 15:47
Hello @sebastianbochan 

i have updated to 2.0.2, and i'm getting the error "'node_modules/@highcharts/highcharts-react-native/highcharts-files/highcharts.js' cannot be loaded as its extension is not registered in assetExts"

 at C:\Users\stron\Desktop\Hex\node_modules\metro\src\Assets.js:356:13

i've tried multiple things including moving the files in readme and deleting that one line of AppEntry but still no success.

**Comment by SchwSimon** [comment] 2019-11-27 09:55
@sebastianbochan I properly installed the latest version 2.0.2, yes I read the Readme and FAQ.

I always clean re-build.
I tried linking the files in multiple ways, always the same error.
Btw due to a current RN issue I can't run `--variant=release` instead for release version I directly assemble a release build.

**Comment by sebastianbochan** [comment] 2019-11-28 14:15
Does it work without using wrapper?

**Comment by okanisildur** [comment] 2020-01-06 11:15
I started to have the same problem with @kot7kz. 
Using expo 36.0.0, highcharts-react-native: 2.1.1, and react-native-webview: 7.4.3

I tried to remove the "main": "node_modules/expo/AppEntry.js" but did not work out.

**Comment by SchwSimon** [comment] 2020-01-09 13:10
@sebastianbochan Are you still working on this issue? We are still paying and waiting to finally use this on production..

**Comment by sebastianbochan** [comment] 2020-01-09 13:43
Can you use the beta branch too? Does it work or not?

Its really specific case, but will test it tomorrow, again.

**Comment by SchwSimon** [comment] 2020-01-13 12:06
@sebastianbochan I have a pretty up to date environment using the default way to init a RN app without expo [(see here: React Native CLI Quickstart)](https://facebook.github.io/react-native/docs/getting-started) or any other special tools or similar.

This is how most rn apps are inited without expo so I would not say that this is a specific case.

**Comment by sebastianbochan** [comment] 2020-01-14 16:35
@SchwSimon,
I created a temporary project in native react-native (according to your advices) and now Im debugging why loading (by CDN) does not work. If will find a reason, then will focus on loading files from local filesystem.

**Comment by sebastianbochan** [comment] 2020-01-15 11:25
@SchwSimon  @okanisildur @kot7kz  are you able to share your simplified apps which uses our wrapper?

**Comment by lee926427** [comment] 2020-02-14 02:15
Hi, I have same qustion and search [#8](https://github.com/highcharts/highcharts-react-native/issues/8#issuecomment-558146884) to find file:///android_asset/highcharts-layout/index.html of line 14 in HighchartsReactNative.js.
so there are not exist file follows path!?

**Comment by ap050492** [comment] 2020-02-17 07:53
> @SchwSimon @okanisildur @kot7kz are you able to share your simplified apps which uses our wrapper?
> 
> I was able to run with the `useCDN / useSSL` flags without any problems.
> 
> <img alt="Zrzut ekranu 2020-01-15 o 12 45 01" width="788" src="https://user-images.githubusercontent.com/2115686/72431431-1dedcd00-3795-11ea-94f3-204380ac4ec3.png">
> 
> ps. I noticed that when I set `flex:1` - webview disappears in the newest 8.0.2 version.
> ps2. The app is only in RN not in Expo.

Facing same issue, Can you please share sample code

**Comment by sebastianbochan** [comment] 2020-02-17 09:21
@ap050492 
Created as additional branch here: https://github.com/highcharts/highcharts-react-native/tree/example-demo/example-app/newrnapp

**Comment by mrinal-roy-au2** [comment] 2020-02-17 11:20
Hey @sebastianbochan 
I copied your ditto App.js file. But got this error. Also you can see my package.json side-by-side with same dependencies.
<img width="1266" alt="Screenshot 2020-02-17 at 4 47 58 PM" src="https://user-images.githubusercontent.com/24915561/74649373-67bb4000-51a5-11ea-86b6-e2b74d3c7ee5.png">

**Comment by oillada** [comment] 2020-02-19 17:24
> Hey @sebastianbochan
> I copied your ditto App.js file. But got this error. Also you can see my package.json side-by-side with same dependencies.
> <img alt="Screenshot 2020-02-17 at 4 47 58 PM" width="1266" src="https://user-images.githubusercontent.com/24915561/74649373-67bb4000-51a5-11ea-86b6-e2b74d3c7ee5.png">

Same issues here

**Comment by oillada** [comment] 2020-02-19 18:23
im faceing the issues only in android simulator, ios work fine, im working on a expo app

> Encountered an error loading page, Object {
  "canGoBack": false,
  "canGoForward": false,
  "code": -1,
  "description": "net::ERR_FILE_NOT_FOUND",
  "loading": false,
  "target": 1143,
  "title": "",
  "url": "file:///android_asset/highcharts-layout/index.html",
}

**Comment by sebastianbochan** [comment] 2020-02-20 11:12
Have you tried to set correct URL by [devPort](https://github.com/highcharts/highcharts-react-native#devPort) option?

**Comment by michaelmeyers** [comment] 2020-03-16 23:06
I too am getting this error on Android only.
   Error loading page
     Domain: Undefined
    Error Code: -1
 Description: net::ERR_FILE_NOT_FOUND

iOS works fine.
Not using Expo.
In my package.json:
 "react": "16.9.0",
"react-native": "0.61.4",
"@highcharts/highcharts-react-native": "2.1.1"

Running on an older device LG-M322.  Android 7.0
currently using useCDN and useSSL to make it run on iOS.
<ChartView styles={styles.container} options={config} useCDN useSSL />

**Comment by sebastianbochan** [comment] 2020-03-17 13:56
Im debugging the problem and will update you when end of the process.

**Comment by sebastianbochan** [comment] 2020-03-18 12:32
Lets keep all informations here: https://github.com/highcharts/highcharts-react-native/issues/51 to avoid duplicates.
