### ISSUE TITLE
Chart not rendering on Android Simulator using EXPO cli

### ISSUE THREAD

**Issue by oillada** [highcharts/highcharts-react-native#51] opened 2020-02-19 18:50 UTC
Hello, i got this issues using android simulator:
<img width="344" alt="Captura de Pantalla 2020-02-19 a la(s) 15 49 00" src="https://user-images.githubusercontent.com/281594/74865102-60c03900-532f-11ea-9d16-ccb680f32aac.png">
On ios device and simulator works fine.

> Encountered an error loading page, Object {
  "canGoBack": false,
  "canGoForward": false,
  "code": -1,
  "description": "net::ERR_FILE_NOT_FOUND",
  "loading": false,
  "target": 1757,
  "title": "",
  "url": "file:///android_asset/highcharts-layout/index.html",
}

Can you help me???

**Comment by sebastianbochan** [comment] 2020-02-20 11:12
HI @oillada,
Have you tried to set correct URL by [devPort](https://github.com/highcharts/highcharts-react-native#devPort) option?

**Comment by oillada** [comment] 2020-02-20 11:15
Can you give me an example of what I hace to set on devPort?

**Comment by oillada** [comment] 2020-02-20 12:37
After changing the devPort to my ip address the error dissapear but the chart is not render. the loading icon shows but the chart never render.
<img width="406" alt="Captura de Pantalla 2020-02-20 a la(s) 09 36 37" src="https://user-images.githubusercontent.com/281594/74934244-89ded900-53c4-11ea-9d5a-859f7f3538e5.png">

**Comment by sebastianbochan** [comment] 2020-02-21 09:23
@oillada,
Can you test iOS and let me know about the results?

**Comment by oillada** [comment] 2020-02-21 12:00
On iOS works fine

**Comment by sebastianbochan** [comment] 2020-02-21 15:50
Will test the android on Monday.

**Comment by sagarp2901** [comment] 2020-03-16 04:29
Facing the exact same issue for Android via all 3 methods - on simulator, directly running on device through expo as well as after building an apk and running on the device. The charts work fine on iOS.
![react-native-chart-error](https://user-images.githubusercontent.com/36165315/76723122-9e409800-671c-11ea-9af5-7d70ab6212ca.png)

Please let me know if you need more details.

**Comment by sebastianbochan** [comment] 2020-03-16 09:35
Have you tried the soltuon from the thread: https://github.com/highcharts/highcharts-react-native/issues/48 ?

**Comment by sagarp2901** [comment] 2020-03-16 22:12
> Have you tried the soltuon from the thread: #48 ?

I couldn't figure out what exactly is the solution there. Its very unclear.

**Comment by VenkatSandy** [comment] 2020-03-17 05:00
same problem here also sir.

**Comment by sebastianbochan** [comment] 2020-03-17 13:56
Im debugging the problem and will update you when end of the process.

**Comment by achieverprince** [comment] 2020-03-18 13:03
+1 i am also stuck in this

**Comment by achieverprince** [comment] 2020-03-18 13:47
@sebastianbochan 

If i follow this section in FAQ it works in android (but i can't debug the application)

**Files are not loaded**
Put the files (i.e. Folder: highcharts-layout and highcharts-files) to android/app/src/main/assets and /ios

Use release mode instead of debug mode run react-native run-android --variant=release

**Comment by achieverprince** [comment] 2020-03-18 14:19
@sebastianbochan 

After running project once with variant 'release'  (and copying files into assets)
Now i am able to run the project even with `npx react-native run-android` without any error.
![image](https://user-images.githubusercontent.com/881066/76970153-74bc8200-6951-11ea-999a-321d027450df.png)

**Comment by sebastianbochan** [comment] 2020-03-18 14:43
Thank you for your feedaback.

I spent a few hours for debugging of the problem and in native expo is problem with dev mode at all. We need to use `expo eject` to have native projects (android and ios) and then copy files  (i.e. Folder: highcharts-layout and highcharts-files) to correct paths `android/app/src/main/assets` and `/ios`

**Comment by achieverprince** [comment] 2020-03-20 05:22
FYI , i am not using expo in my project.

**Comment by sebastianbochan** [comment] 2020-03-20 08:31
@achieverprince its does not matter if you use expo or not, you should place `highcharts-layout` and `highcharts-files` in the correct path. Its related with fact that the base of wrapper is `react-native-webview` which required do that (in their official docs) -> https://github.com/react-native-community/react-native-webview

**Comment by apswak** [comment] 2020-04-13 13:43
Planned on moving over from `react-native-highcharts` and also getting this, are there any plans to support expo? Or is ejecting necessary

**Comment by sebastianbochan** [comment] 2020-04-14 11:32
Ejecting is necessary for android.

**Comment by jgeliberte** [comment] 2020-05-04 21:18
Im experiencing the same issue, i was wondering what is the final solution for this problem? and can u provide a step by step implementation of the solution?
Thanks.

**Comment by jgeliberte** [comment] 2020-05-04 22:09
> Im experiencing the same issue, i was wondering what is the final solution for this problem? and can u provide a step by step implementation of the solution?
> Thanks.

i was able to import it properly and moved the folders to my /src/assets folder.
The next problem is the chart is not rendering at all, just blank screen.

**Comment by MaximMalyavko85** [comment] 2020-05-21 12:25
+1 for android: Error loading page Domain :undefined Error Code:-1 Description:net::ERR_FILE_NOT_FOUND
can you tell me  step by step, how fixed this.

**Comment by JsonGuy** [comment] 2020-05-22 11:44
@MaximMalyavko85 
![image](https://user-images.githubusercontent.com/20183140/82664571-a3e5bd00-9c3a-11ea-90fa-53ae1f700703.png)

Like this, copy those 2 folderns from node_modules highcharts directory, this fixed the error for me

**Comment by MaximMalyavko85** [comment] 2020-05-22 14:16
> @MaximMalyavko85
> ![image](https://user-images.githubusercontent.com/20183140/82664571-a3e5bd00-9c3a-11ea-90fa-53ae1f700703.png)
> 
> Like this, copy those 2 folders (highchart-files, highchart-layout) from node_modules highcharts directory, this fixed the error for me

no, for me this is not work. Is are any ideas?

**Comment by cnsnmms** [comment] 2020-05-24 09:12
Please add the below  lines to build.gradle file

    sourceSets {
      main {
        assets {
          srcDirs += ['src/main/assets/']
        }
      }
    }

**Comment by MaximMalyavko85** [comment] 2020-05-25 08:37
its a worried, but after add this line, charts not rendering same. 
I am will do step by step all. Was i have any error.
1. I removed all node_modules and install yarn add @highcharts/highcharts-react-native (because npm install geted error with package name)
2. I added to folders (highcharts-files, highcharts-layout) in android/app/src/main/assets
<img width="281" alt="Снимок экрана 2020-05-25 в 11 25 06" src="https://user-images.githubusercontent.com/25934359/82794616-6fad0f00-9e7b-11ea-858e-400cf8b3cc64.png">
3. I added this lines to build.gradle.
<img width="1054" alt="Снимок экрана 2020-05-25 в 11 27 43" src="https://user-images.githubusercontent.com/25934359/82794640-7b003a80-9e7b-11ea-84f4-3b6580364e4c.png">
4. My main code for charts 
`export default class Chart extends React.Component {
constructor(props){
		super(props)
		    this.state = {
			chartOptions: {
					series: [{
							data: [1, 2, 3]
					}]
			}
	         };
	}
    render(){
      <View>
        <HighchartsReactNative
        	styles={styles.container}
          options={this.state.chartOptions}
        />
      </View>
    }
}

const styles = StyleSheet.create({
	container: {
			backgroundColor: '#fff',
			justifyContent: 'center'
	}
});
`
Not work in expo simulater, in real devices and after buid version in real devices.
Have any ideas?

**Comment by MaximMalyavko85** [comment] 2020-05-26 16:00
Also i create new expo project. 
Downloaded @highcharts/highcharts-react-native.
Set build.gradle, how pointed top, relocated 2 folders, how pointed top.
And geted same problem: 
Encountered an error loading page, Object {
  "canGoBack": false,
  "canGoForward": false,
  "code": -1,
  "description": "net::ERR_FILE_NOT_FOUND",
  "loading": false,
  "target": 3,
  "title": "",
  "url": "file:///android_asset/highcharts-layout/index.html",
}

I appeal to contributors @highcharts/highcharts-react-native. 
Team, help me. Why i geted this problem. In resources i am not geting answer for this question. This is bug?

**Comment by sebastianbochan** [comment] 2020-06-09 10:38
Have you tried to `useCDN` / `useSSL` params to verify if its problem with local files or general app issue?

**Comment by MaximMalyavko85** [comment] 2020-06-10 08:05
Yes. I added params useCDN and useSSL to teg chart, how you see in the top screen. But this not work. Also i lowered SDK version, but it not worked.

**Comment by KarlaSaenz** [comment] 2020-07-06 00:39
+1 for this issue. I am using expo in my project, added params useCDN and useSSL but this not work in android only ios. I changed the devPath to my ip address the error dissapear but the chart is not render. Do you have any idea?

**Comment by tony-aq** [comment] 2020-07-07 13:40
To reproduce ERR_FILE_NOT_FOUND I follow steps outlined in highcharts blog post:
https://www.highcharts.com/blog/post/creating-mobile-charts-with-highcharts-react-native/

What steps are required to make this blog post example work?

Dependencies I worked from:
```
  "dependencies": {
    "@highcharts/highcharts-react-native": "^2.2.1",
    "expo": "~38.0.8",
    "expo-status-bar": "^1.0.2",
    "react": "~16.11.0",
    "react-dom": "~16.11.0",
    "react-native": "https://github.com/expo/react-native/archive/sdk-38.0.1.tar.gz",
    "react-native-web": "~0.11.7",
    "react-native-webview": "9.4.0"
  },
```

**Comment by samimhakimi** [comment] 2020-07-09 08:54
Any one solved this issue till now or not?

Encountered an error loading page, Object {
"canGoBack": false,
"canGoForward": false,
"code": -1,
"description": "net::ERR_FILE_NOT_FOUND",
"loading": false,
"target": 1757,
"title": "",
"url": "file:///android_asset/highcharts-layout/index.html",
}

> Hello, i got this issues using android simulator:
> <img alt="Captura de Pantalla 2020-02-19 a la(s) 15 49 00" width="344" src="https://user-images.githubusercontent.com/281594/74865102-60c03900-532f-11ea-9d16-ccb680f32aac.png">
> On ios device and simulator works fine.
> 
> > Encountered an error loading page, Object {
> > "canGoBack": false,
> > "canGoForward": false,
> > "code": -1,
> > "description": "net::ERR_FILE_NOT_FOUND",
> > "loading": false,
> > "target": 1757,
> > "title": "",
> > "url": "file:///android_asset/highcharts-layout/index.html",
> > }
> 
> Can you help me???

Any one solved this issue or not?

**Comment by sebastianbochan** [comment] 2020-07-15 07:32
We are wokring on that and debugging the problem. Can be related with new versions of modules.

Thankfully, we are able to reproduce the problem.

I will inform you about progress, when find a reason of issue.

**Comment by hyper750** [comment] 2020-07-16 11:36
On this [line](https://github.com/highcharts/highcharts-react-native/blob/master/dist/src/HighchartsReactNative.js#L41) is using `props.devPath` instead of `props.devPort`, by default is using `file://`. When I change `devPath` to my IP and port (X.X.X.X:19000) the error disappears, but the chart is empty.

**Comment by hyper750** [comment] 2020-07-16 13:43
Specifying the `http` protocol for `devPath` (`http://X.X.X.X:19001`) I get the following error insde the chart.

![image](https://user-images.githubusercontent.com/29048245/87678089-d1527100-c77a-11ea-80ee-af7ccce3ec8d.png)

**Comment by hyper750** [comment] 2020-07-17 11:47
Modifying the property `highchartsLayout` inside `HighchartsReactNative` to the following code the html works, I don't know why but there's an `alert('a')` inside the `highcharts-layout/index.html`. The chart is still not working, but is rendering the `html`.

```javascript
highchartsLayout = { uri: 'file:///android_asset/highcharts-layout/index.html' };
if(Platform.OS == 'ios'){
    highchartsLayout = require('../highcharts-layout/index.html')
}
else if(props.devPath){
    highchartsLayout = { uri: props.devPath + '/node_modules/@highcharts/highcharts-react-native/highcharts-layout/index.html' };
}
```

![image](https://user-images.githubusercontent.com/29048245/87782914-b7c13000-c833-11ea-947b-b66440eedc5b.png)

**Comment by sebastianbochan** [comment] 2020-07-21 07:48
We are still testing the beta-version, which fix all these kind of problems and should be released in the end of this week.

**Comment by sebastianbochan** [comment] 2020-07-23 14:09
We just finished testing the wrapper and released the beta version which is available here https://github.com/highcharts/highcharts-react-native/tree/beta-3

Any feedback will be really helpful.

Please keep in mind, that all packages should be in the latest versions of them. Number of versions are declared also in the `package.json` file.

**Comment by axelav** [comment] 2020-07-31 19:35
Any progress on getting this released? I'm trying to test this `beta-3` branch but I'm unable to get it to run.

```
Failed building JavaScript bundle.
While trying to resolve module `@highcharts/highcharts-react-native` from file `/Users/axel/s/pillar/hermes/src/components/charts/AlertChart.js`, the package `/Users/axel/s/pillar/hermes/node_modules/@highcharts/highcharts-react-native/package.json` was successfully found. However, this package itself specifies a `main` module field that could not be resolved (`/Users/axel/s/pillar/hermes/node_modules/@highcharts/highcharts-react-native/node_modules/expo/AppEntry.js`. Indeed, none of these files exist:

  * /Users/axel/s/pillar/hermes/node_modules/@highcharts/highcharts-react-native/node_modules/expo/AppEntry.js(.native|.ios.expo.ts|.native.expo.ts|.expo.ts|.ios.expo.tsx|.native.expo.tsx|.expo.tsx|.ios.expo.js|.native.expo.js|.expo.js|.ios.expo.jsx|.native.expo.jsx|.expo.jsx|.ios.ts|.native.ts|.ts|.ios.tsx|.native.tsx|.tsx|.ios.js|.native.js|.js|.ios.jsx|.native.jsx|.jsx|.ios.json|.native.json|.json|.ios.wasm|.native.wasm|.wasm)
  * /Users/axel/s/pillar/hermes/node_modules/@highcharts/highcharts-react-native/node_modules/expo/AppEntry.js/index(.native|.ios.expo.ts|.native.expo.ts|.expo.ts|.ios.expo.tsx|.native.expo.tsx|.expo.tsx|.ios.expo.js|.native.expo.js|.expo.js|.ios.expo.jsx|.native.expo.jsx|.expo.jsx|.ios.ts|.native.ts|.ts|.ios.tsx|.native.tsx|.tsx|.ios.js|.native.js|.js|.ios.jsx|.native.jsx|.jsx|.ios.json|.native.json|.json|.ios.wasm|.native.wasm|.wasm)
```

**Comment by sebastianbochan** [comment] 2020-08-03 11:59
The new 3.0 version is released. 

Im closing this ticket. If you will encounter any problems, please create a new ticket. In this case we will avoid confusing and keep the newest version on track.

**Closed by sebastianbochan** 2020-08-03 11:59 UTC

**Comment by aditya1711** [comment] 2020-09-14 17:11
> HI @oillada,
> Have you tried to set correct URL by [devPort](https://github.com/highcharts/highcharts-react-native#devPort) option?

What should be the correct URL for this? Further, how should I debug? 

Thanks in advance for this.

**Comment by sebastianbochan** [comment] 2020-10-08 07:39
The devPort is a url of your expo server.

<img width="289" alt="Zrzut ekranu 2020-10-8 o 09 38 59" src="https://user-images.githubusercontent.com/2115686/95429089-3072ec80-094a-11eb-8b1e-6fde4be892ec.png">
